name: Build Python MapScript Wheels

on: [push]

jobs:
  build:

    runs-on: windows-2022 # includes VS 2022
    strategy:
      matrix:
        python-version: [2.7] # , 3.6, 3.7, 3.8, 3.9

    steps:   
      - uses: actions/checkout@master
        with:
          name: mapserver/mapserver
          ref: main
          
      - name: Download and unzip SDK
        shell: ps
        # http://download.gisinternals.com/sdk/downloads/release-1930-x64-dev.zip
        run: |
          $SDK="release-1930-x64"
          $SDK_ZIP="$SDK-dev.zip"
          $SDK_URL="http://download.gisinternals.com/sdk/downloads/$SDK_ZIP"
          mkdir sdk
          Invoke-WebRequest -Uri $SDK_URL -OutFile $SDK_ZIP
          Expand-Archive $SDK_ZIP -DestinationPath sdk
          
      - name: Build MapServer
        shell: ps
        run: |          
          $BUILD_FOLDER = "${{ github.workspace }}"         
          $SDK_PREFIX="$BUILD_FOLDER/sdk/SDK"
          $SDK_INC="$BUILD_FOLDER/sdk/$SDK/include"
          $SDK_LIB="$BUILD_FOLDER/sdk/$SDK/lib"
          $SDK_BIN="$BUILD_FOLDER/sdk/$SDK/bin"
          $SWIG_EXECUTABLE="$BUILD_FOLDER/sdk/swig.exe"
          $REGEX_DIR="$BUILD_FOLDER/sdk/support/regex-0.12"
          mkdir build
          cd build
          $env:Path = "$BUILD_FOLDER/build/Release;$SDK_BIN;' + $env:Path
          $PROJECT_BINARY_DIR="$BUILD_FOLDER/build"
          cmake -G "Visual Studio 17 2022" -A "x64" .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$SDK_PREFIX -DPNG_LIBRARY=$SDK_LIB/libpng16_static.lib -DHARFBUZZ_INCLUDE_DIR=$SDK_INC/harfbuzz -DICONV_DLL=$SDK_BIN/iconv.dll -DFRIBIDI_INCLUDE_DIR=$SDK_INC/fribidi -DMS_EXTERNAL_LIBS=$SDK_LIB/harfbuzz.lib;$SDK_LIB/uriparser.lib -DSVG_LIBRARY=$SDK_LIB/libsvg.lib -DSVGCAIRO_LIBRARY=$SDK_LIB/libsvg-cairo.lib -DREGEX_DIR=$REGEX_DIR -DSWIG_EXECUTABLE=$SWIG_EXECUTABLE -DPROTOBUFC_COMPILER=$SDK_BIN/protoc.exe -DPROTOBUFC_LIBRARY=$SDK_LIB/protobuf-c.lib -DPROTOBUFC_INCLUDE_DIR=$SDK_INC/protobuf-c -DWITH_CURL=1 -DWITH_KML=1 -DWITH_SVGCAIRO=1 -DWITH_THREAD_SAFETY=1 -DWITH_SOS=1 -DWITH_CLIENT_WFS=1 -DWITH_CLIENT_WMS=1-DWITH_CSHARP=1 -DWITH_PROTOBUFC=1 -DWITH_POSTGIS=0 -DWITH_PERL=0 -DWITH_MSSQL2008=1 -DWITH_PYTHON=1 -DWITH_PHPNG=0 -DWITH_HARFBUZZ=1 -DMAPSCRIPT_PROPERTYANNOTATIONS=1 -DPROJ_INCLUDE_DIR=$SDK_INC/proj7
          
#  publish:
#    name: Publish to PyPI
#    needs: test
#    runs-on: ubuntu-latest
#    container: python:3-slim
#    steps:
#      - name: Publish package
#        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_API_TOKEN }}

# https://stackoverflow.com/questions/65300378/how-can-i-download-the-build-file-from-github-actions