name: Build Python MapScript Wheels

on: [push]
env:
  SDK: "release-1930-x64"
  VS_VER: "Visual Studio 17 2022"
  VC_VARS: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars64.bat"

  SWIG_VER: "4.2.1"

jobs:
  build:

    runs-on: windows-2022 # includes VS 2022
    #runs-on: windows-2019 # includes VS 2019
    strategy:
      fail-fast: true # default is true, set to false to see which builds run
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11, 3.12] # "3.10" needs to be in quotes

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Get MapServer sourcecode
        shell: powershell
        run: |
          # git clone https://github.com/mapserver/mapserver.git --branch main --single-branch mapserver
          git clone https://github.com/mapserver/mapserver.git --branch rel-8-2-0 --single-branch mapserver
          
      - name: Download and unzip SDK
        shell: powershell        
        run: ./scripts/download-sdk.ps1 -SDK $env:SDK -SWIG_VER $env:SWIG_VER

      - name: Configure MapServer
        shell: powershell
        run: |
        ./scripts/configure-mapserver.ps1 `
          -SDK $env:SDK `
          -SWIG_VER $env:SWIG_VER `
          -VS_VER $env:VS_VER `
          -VCVARS $env:VC_VARS `
          -PYTHON_LOCATION $env:pythonLocation `
          -PYTHON_VERSION $matrix.python-version

      - name: Add Wheels and source files to repo
        #if: always() # always upload any files for debugging
        # only check-in the wheels if the keyword upload-wheels is present in the commit message
        if: contains(github.event.head_commit.message, 'upload-wheels')
        shell: powershell
        run: ./scripts/add-wheels.ps1 -PYTHON_VERSION $matrix.python-version


#  publish:
#    name: Publish to PyPI
#    needs: test
#    runs-on: ubuntu-latest
#    container: python:3-slim
#    steps:
#      - name: Publish package
#        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_API_TOKEN }}

# https://stackoverflow.com/questions/65300378/how-can-i-download-the-build-file-from-github-actions